### ISSUE TITLE
[Feature]: add JSON output format

### ISSUE THREAD

**Issue by retzkek** [xitonix/trubka#10]
Consider adding JSON output format. For better or worse it's now the standard data interchange, and with tools like `jq` is easily manipulated, filtered, etc. This would be especially useful for creating input to tools like `kafka-reassign-partitions.sh`. For reference here's what that looks like, first for input to `--topics-to-move-json-file`:
```json
{
  "topics": [
    {
      "topic": "topic1" 
    },
    {
      "topic": "topic2" 
    },
    {
      "topic": "topic3" 
    }
  ],
  "version": 1
}
```

Then for input to `--reassignment-json-file`:

```json
{
  "version": 1,
  "partitions": [
    {
      "topic": "topic1",
      "partition": 0,
      "replicas": [1, 2],
      "log_dirs": ["any","any"]
    },
    {
      "topic": "topic2",
      "partition": 0,
      "replicas": [2, 3],
      "log_dirs": ["any","any"]
    },
    {
      "topic": "topic3",
      "partition": 0,
      "replicas": [1, 3],
      "log_dirs": ["any","any"]
    }
  ]
}
```

**Comment by xitonix** [comment]
Thanks for opening the feature request @retzkek . Having json format is absolutely beneficial and I will add it soon. That said, the above schema seems specific to `kafka-reassign-partitions.sh` I believe. Any valid json output can be translated into a desired schema using `jq` filters and variables. What's your opinion on this?

**Comment by retzkek** [comment]
Oh definitely I agree, just illustrating a few uses in the current tooling.

**Comment by xitonix** [comment]
I just release a new version with `json`, `plain` and `list` output formats @retzkek . Please give it a shot and let me know what you think mate.

**Comment by retzkek** [comment]
Thanks! So I'm a bit torn here, I like the colorized/formatted output, but then the point of JSON normally is for machine interop, which it breaks due to the ANSI codes. 

```
± trubka list topics -f json | jq
parse error: Invalid numeric literal at line 3, column 6
```

I see there's a `--no-colour` option, but maybe for JSON it should be the default?

**Comment by xitonix** [comment]
Makes sense I suppose. At least for the admin commands.

**Comment by xitonix** [comment]
Hi @retzkek,

Colours are now disabled by default for the json output. I'm going to go ahead and close this feature request now.
