### ISSUE TITLE
[BUG]: Using TRUBKA_PROTO_ROOT does not work

### ISSUE THREAD

**Issue by MahlerFive** [xitonix/trubka#16]
**Describe the bug**
Setting TRUBKA_PROTO_ROOT environment variable still gives an error about requiring the `--proto-root` flag.

**To Reproduce**

```
$ echo $TRUBKA_PROTO_ROOT
/Users/jeff/dev/platypus

$ trubka consume proto --topic-filter wifi --proto-filter Blip --brokers localhost:9092 --kafka-version 2.2.0 -i
ERROR: Required flag --proto-root not provided
```

**Expected behavior**
If I provide this environment variable I shouldn't have to provide `--proto-root`. According to the wiki:

```
It is possible to ask Trubka to read the cli flags from the system's environment variables. The flags must be in TRUBKA_FLAG_NAME format. For example the value of --proto-root parameter can be read from TRUBKA_PROTO_ROOT if it's provided.
```

**Comment by xitonix** [comment]
Hi Jeff,

May I ask what operating system you are using? That's exactly what I do every day without any issue. I tried to combine all the parameters you mentioned above (including the version) and it works perfectly fine on my machine. Also, that would be great if you could please post the output of the following commands here as well:
`env | grep TRUBKA` and `ls -al /Users/jeff/dev/platypus`

**Comment by MahlerFive** [comment]
Not on that machine at the moment to get that output, but it's running the latest Mac OS (Catalina?).

If I run the exact same command with `--proto-root ./` while in that directory, it works fine.

**Comment by MahlerFive** [comment]
My mistake. Turns out I had merely set the variable but not exported to the env. Running `env | grep TRUBKA` showed it was missing. Once I exported it, it worked fine.
