### ISSUE TITLE
[Feature]: Add a --to parameter to consumer

### ISSUE THREAD

**Issue by MahlerFive** [xitonix/trubka#17]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a `--to` parameter in the consumer.
One benefit is that you can pipe your consumed messages to a file and the consumer will finish once the `--to` condition is reached.
Another benefit is that if you're searching through messages, it allows you to narrow your search.

**Describe the solution you'd like**
The ability to stop consuming by timestamp, by latest offset at the time of starting the consumer, and/or by specific offsets by partition.

For example you could consume messages between 3pm and 4pm like:

`$ trubka consume plain <topic name> --brokers <broker:port> --from 22-02-2020T15:00:00 --to 22-02-2020T16:00:00`

Or you could consume messages from 3pm until now like:

`$ trubka consume plain <topic name> --brokers <broker:port> --from 22-02-2020T15:0:00 --to newest`

**Comment by xitonix** [comment]
Thanks for opening the feature request @MahlerFive . This is a bit tricky as offsets are bound to the partitions and you don't really know when to stop the whole consuming process. Let's say partition 1 has an offset on `22-02-2020T16:00:00` but partition 2 does not have any message with that timestamp. When would you stop consuming? I will put more thoughts on this to see if I can find a solution because I agree with you that it could be a very useful feature to have.

**Comment by MahlerFive** [comment]
I suppose you'd have to wait until there was at least one message with a greater timestamp in each partition to stop. If the timestamp is in the past, you could just stop at newest if you never see a message with a greater timestamp.

I suppose I've never really run into this problem with the other tool I use because I'm either investigating something that happened a while ago or the topic has fairly high throughput anyway. I checked how it was implemented in that tool and it just waits to see a message with greater timestamp.

**Comment by xitonix** [comment]
Hi @MahlerFive . I just released v3.1.2 with `--to` flag. Please pull the latest version and let me know what you think. You can also find the updated docs [here](https://github.com/xitonix/trubka/wiki/Consume-from-Kafka#offset-management)-Thanks.

**Comment by xitonix** [comment]
Closing the FR. Released in v3.1.2.
