### ISSUE TITLE
[Question]: How do you define the partition key

### ISSUE THREAD

**Issue by kdawgwilk** [xitonix/trubka#21]
I am wanting to be explicit about the partition key when publishing with trubka and I have not been able to figure out how I can specify that

**Comment by xitonix** [comment]
You cannot define the partition you want to publish to I'm afraid, but you can specify the partition key using `-k, --key` flag. All of your messages will be landing in the same partition if the key is explicitly defined.

**Comment by kdawgwilk** [comment]
Thanks for the quick response!
