### ISSUE TITLE
List topic lag?

### ISSUE THREAD

**Issue by dnaeon** [xitonix/trubka#8]
Thanks for making this one, really neat!

Is there a way to get the lag per topic?

Thanks!

**Comment by xitonix** [comment]
Thanks @dnaeon. If I understood you correctly, `trubka list group-offsets <group_name>` will give you the lag for all the topics under that consumer group. You can also check the local offsets for a specific topic using`trubka list local-offsets <topic>` command. Hope that's answered your question.

**Comment by dnaeon** [comment]
Great, thanks!
