### ISSUE TITLE
[Feature]: Make "plain" list output plainer

### ISSUE THREAD

**Issue by retzkek** [xitonix/trubka#9]
Plain text output is often very useful, and allows for output to be piped to standard unix tools for manipulation. However, the current "plain" output format has some decoration that impedes this, e.g.

```
$ trubka list topics -f plain
Topics (96)
───────────
 ● __consumer_offsets
 ● topic1
 ● topic2
 ● topic3
[...]

 Total
─────
    Topics: 96
Partitions: 180
```

Please change `plain`, or add a different output format, that is just a simple plain-text list, with no decoration, headers, or footers, e.g.

```
$ trubka list topics -f plain
topic1
topic2
topic3
```

**Comment by xitonix** [comment]
Done. Please install `v3.1.0`.

**Comment by retzkek** [comment]
Thanks for the quick response! There's still a header and footer with `plain` though, can we get rid of those?

```
± trubka list topics -f plain
Topics (96)
  __consumer_offsets
...

SUMMARY: 180 partitions in 96 topics
```

**Comment by xitonix** [comment]
Thanks Kevin. May I ask what's your intended use for plain text mode? I personally don't think having undecorated headers and footers would make the output none plain. What sort of commands you would pipe the output in?

**Comment by retzkek** [comment]
I'd like to be able to pass the output to tools like`grep` (or more notably `grep -v`), `sort`, `xargs`, etc, and not have to worry about stripping out anything that's not a topic (or consumer group, etc) . Or to quote the [Unix philosophy](http://www.catb.org/esr/writings/taoup/html/ch01s06.html):

> Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. Don't insist on interactive input.

**Comment by xitonix** [comment]
I get your point, but I need to find a way to represent plain text without sacrificing the clarity. Not all the commands are returning a single type of entity. Titles and indentations are used to explain what they are and how they relate to each other. Here is an example:
`trubka describe group cg -f plain -m`

```
         Name: cg
  Coordinator: 1.1.10.10
        State:  Stable
     Protocol: range
Protocol Type: consumer

Members (2)

cg-0cf38b4f-ce3b-448a-9f79-c71805ddbcfb (1.10.10.10)
Assignments (2)
  topic-1: 0,1
  topic-2: 2,3

cg-17fa-44f4-9db1-f86e2501817c (1.10.10.11)
Assignments (2)
  topic-1: 2,3
  topic-2: 0,1
```

**Comment by retzkek** [comment]
That's a fair point, and worth some thought. From a CLI/API consumer perspective my expectation is that a `list x` command will return just a list of xs, while I don't have much expectation for what a `describe` command would return (the very name suggests something human-readable). There just as easily could be a `list group-members <group>` command, etc...

For some of the more complicated responses you could look at the `docker` commands for example, where the `--format` option takes a go template string to allow customization of the output. 

But then on the other hand now that JSON output is available (#10) I could easily use jq to create whatever format I wanted. `trubka list topics -f json --no-colour | jq -r '.[].name' | ...` is a bit more awkward but certainly works.

**Comment by xitonix** [comment]
Thanks for sharing your thoughts mate. I really appreciate it. Certainly need to spend some time to find a middle ground so that we don't end up with so many commands and yet keep the compatibility with `json` and `list` formats. Will keep you posted. :)

**Comment by xitonix** [comment]
I decided to go with a middle ground approach by removing the clutter from the list sub-commands and tiding up the describe sub-commands as much as possible. I found the output very confusing if I removed all the indentations. That means, I decided to keep `plain` as plain as possible but still a human readable format. Please give it another shot and let me know what you think before I close off the request mate. Thanks a lot.

**Comment by retzkek** [comment]
Yeah this looks good to me, thanks a lot!
